name: build-images
on: workflow_dispatch

jobs:
  linux:
    strategy:
      matrix:
        arch: [amd64, arm64]

    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make linux-${{ matrix.arch }}
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push
        run: make push-linux-${{ matrix.arch }}
