name: build
on:
  push:
  schedule:
    - cron: '30 3 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: rbernon/winehq:latest
      options: --user root
    strategy:
      matrix:
        arch: [win32, win64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: .ccache
          key:
            cache-linux-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            cache-linux-${{ matrix.arch }}
            cache-${{ matrix.arch }}

      - name: Build
        run: |
          $PWD/build-linux ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build-linux-${{ matrix.arch }}
          path: usr

  test-linux:
    needs: [build-linux]
    runs-on: ubuntu-latest
    container:
      image: rbernon/winehq:latest
      options: --user root
    strategy:
      matrix:
        arch: [win32, win64]
        test: [nulldrv, desktop, fvwm, openbox, kwin, mutter, wayland, vulkan]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: build-linux-${{ matrix.arch }}

      - name: Test
        run: |
          chmod +x local/bin/*
          useradd github && mkdir -p /home/github /home/github/Documents /home/github/Desktop && chown github:github -R /home/github
          su - github $PWD/test-linux $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ github.event_name }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: test-linux-${{ matrix.test }}-${{ matrix.arch }}.report
          path: /home/github/*.report

  clean:
    needs: [test-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
