name: build-macos
on:
  workflow_call:
    inputs:
      commit:
        type: string
        default: "origin/master"

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [win64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            .ccache
            wine
          key:
            cache-macos-${{ matrix.arch }}-${{ github.run_id }}
          restore-keys: |
            cache-macos-${{ matrix.arch }}

      - name: Install Brew
        run: |
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          eval "$(/usr/local/bin/brew shellenv)"

          arch -x86_64 brew list --formula | xargs arch -x86_64 brew uninstall -f --ignore-dependencies
          ls $HOMEBREW_PREFIX/bin | grep -v brew | xargs -I{} rm $HOMEBREW_PREFIX/bin/{}
          arch -x86_64 brew update
          arch -x86_64 brew bundle

      - name: Build
        run: |
          arch -x86_64 $PWD/build-macos ${{ matrix.arch }} ${{ inputs.commit }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: build-macos-${{ matrix.arch }}
          path: usr
