name: nightly
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  winetest:
    if: ${{ endsWith(github.repository, 'winetest') }}
    uses: ./.github/workflows/winetest.yml
    secrets: inherit
    with:
      commit: origin/master
      event: schedule

  clean:
    needs: winetest
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        uses: rbernon/workflow-cleanup@main
        with:
          workflow: all
