name: tests-macos
on:
  workflow_call:
    inputs:
      event:
        type: string
        default: "push"

jobs:
  test-macos:
    runs-on: macos-13
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch: [win64]
        test: [opengl, vulkan]
        include:
          - arch: wow64
            test: opengl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build-macos-win64

      - name: Install Brew
        run: |
          BREWPREFIX=$(brew --prefix)
          brew list --formula | xargs brew uninstall -f --ignore-dependencies
          ls $BREWPREFIX/bin | grep -v brew | xargs -I{} rm $BREWPREFIX/bin/{}
          brew update
          brew bundle

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          $PWD/test-macos $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ inputs.event }}

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-macos-${{ matrix.test }}-${{ matrix.arch }}.report
          path: macos-*.report

  test-macos-m1ros2:
    runs-on: macos-14
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch: [win64, wow64]
        test: [m1ros2-vulkan]
        include:
          - arch: wow64
            test: m1ros2-opengl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build-macos-win64

      - name: Install Brew
        run: |
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          eval "$(/usr/local/bin/brew shellenv)"

          BREWPREFIX=$(arch -x86_64 brew --prefix)
          arch -x86_64 brew list --formula | xargs arch -x86_64 brew uninstall -f --ignore-dependencies
          ls $BREWPREFIX/bin | grep -v brew | xargs -I{} rm $BREWPREFIX/bin/{}
          arch -x86_64 brew update
          arch -x86_64 brew bundle

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          arch -x86_64 $PWD/test-macos $PWD ${{ matrix.arch }} ${{ matrix.test }} ${{ inputs.event }}

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-macos-${{ matrix.test }}-${{ matrix.arch }}.report
          path: m1ros2-*.report
