name: tests-macos
on:
  workflow_call:
    inputs:
      event:
        type: string
        default: "push"

jobs:
  test-macos:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15]
        arch: [win64, wow64]
        test: [opengl, vulkan]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: build-macos-win64

      - name: Install Brew
        run: |
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          eval "$(/usr/local/bin/brew shellenv)"

          arch -x86_64 brew list --formula | xargs arch -x86_64 brew uninstall -f --ignore-dependencies
          ls $HOMEBREW_PREFIX/bin | grep -v brew | xargs -I{} rm $HOMEBREW_PREFIX/bin/{}
          arch -x86_64 brew update
          arch -x86_64 brew bundle

      - name: Test
        run: |
          chmod +x local/bin/* local/lib/wine/*-unix/wine*
          arch -x86_64 $PWD/test-macos $PWD ${{ matrix.arch }} ${{ matrix.os }}-${{ matrix.test }} ${{ inputs.event }}

      - name: Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-${{ matrix.os }}-${{ matrix.test }}-${{ matrix.arch }}.report
          path: macos-*.report
